### ISSUE TITLE
Dockerfile and dependency versions

### ISSUE THREAD

**Issue by iferres** [milnus/Corekaburra#13]
The Dockerfile grabs the `requirements-dev.txt` file to override some dependency versions, but no versions are declared in some of the them in that file. Maybe is a good idea to explicitly declare them to improve reproducibility. Even better would be to provide a prebuilt docker container in any container library (e.g. docker-hub, GitHub packages, etc) as it would improve usability, but this last thing is just a recommendation for the future, not needed for complete the JOSS review.

I got the same error as reported in #12 when installing with `conda`.

`pip` installs ok.

**Comment by iferres** [comment]
Linking https://github.com/openjournals/joss-reviews/issues/4910

**Comment by milnus** [comment]
[DockerHub repository](hub.docker.com/repository/docker/magnusgj/corekaburra) had been constructed and added into the README, and Qucik-start and Docker wiki pages

**Comment by iferres** [comment]
The docker image works ok, thanks! Closing this issue.

**Comment by iferres** [comment]
This is just to improve the experience, don't take it as part of the review, but I use [apptainer](https://apptainer.org/) (former singularity) to build and run my containers on the institution server where I work and I see there's a lot of room to shrink the image size (`.sif` files):
![imagen](https://user-images.githubusercontent.com/26774127/201678517-dced70fd-9c2b-4c69-a021-57db7d90c693.png)
The apptainer recipe I used to generate the smaller `.sif` was:
```
Bootstrap: docker
From: debian:11.5-slim

%post
   apt-get update -y && apt-get install python3-pip -y
   pip install corekaburra
```
The dockerfiles are a bit different but it should be easy to read and understand what I did. I used a very small debian as base image, then I installed pip, and then I install corekaburra with it.
It should also facilitate the maintenance of the containers since you could basically only actively maintain it with pip or conda.
For conda, I frequently use [this](https://hub.docker.com/r/continuumio/miniconda3) base image, or the [mamba project](https://hub.docker.com/r/mambaorg/micromamba) one which provides a much faster environment solver than conda's.
Hope it helps!
